#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

GPU_INDEX="${GPU_INDEX:-1}"
PORT="${PORT:-18421}"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
LABEL="${LABEL:-gemma4-q8-gpu${GPU_INDEX}-vdr2-selecteddown-reordervdr2-full512-${STAMP}}"
MTP_DRAFT_MODEL="${MTP_DRAFT_MODEL:-/mnt/fast-ai/llm-models/gemma4-26b-a4b-it-q8-gguf/MTP/gemma-4-26B-A4B-it-Q4_0-MTP.gguf}"
if [[ -z "${EXTRA_LLAMA_ARGS:-}" && ! -f "$MTP_DRAFT_MODEL" ]]; then
  echo "[gemma4-record] Q4_0 MTP draft not found: $MTP_DRAFT_MODEL" >&2
  echo "[gemma4-record] set MTP_DRAFT_MODEL to the draft produced by repro/gemma4-26b-a4b-q8-b70-125tps-20260701/prepare-draft.sh" >&2
  exit 2
fi

LLAMA_SERVER="${LLAMA_SERVER:-/home/steve/src/llama.cpp-gemma-record-repro-c926/build-sycl-b70-aot-bmg-g31-q8reorder-vdr2/bin/llama-server}" \
ONEAPI_DEVICE_SELECTOR="${ONEAPI_DEVICE_SELECTOR:-level_zero:${GPU_INDEX}}" \
UR_L0_USE_IMMEDIATE_COMMANDLISTS="${UR_L0_USE_IMMEDIATE_COMMANDLISTS:-1}" \
GGML_SYCL_DISABLE_OPT="${GGML_SYCL_DISABLE_OPT:-0}" \
GGML_SYCL_DISABLE_GRAPH="${GGML_SYCL_DISABLE_GRAPH:-0}" \
GGML_SYCL_ENABLE_VMM="${GGML_SYCL_ENABLE_VMM:-0}" \
LLAMA_SYCL_MUL_MAT_ID_MULTI_TOKEN_FAST="${LLAMA_SYCL_MUL_MAT_ID_MULTI_TOKEN_FAST:-1}" \
LLAMA_SYCL_MUL_MAT_ID_Q8_0_REORDER="${LLAMA_SYCL_MUL_MAT_ID_Q8_0_REORDER:-1}" \
LLAMA_SYCL_MUL_MAT_ID_Q8_0_REORDER_DIRECT_VDR2="${LLAMA_SYCL_MUL_MAT_ID_Q8_0_REORDER_DIRECT_VDR2:-1}" \
LLAMA_SPEC_VERIFY_BACKEND_ARGMAX_IDS="${LLAMA_SPEC_VERIFY_BACKEND_ARGMAX_IDS:-1}" \
LLAMA_SPEC_VERIFY_BACKEND_ARGMAX_SCORES="${LLAMA_SPEC_VERIFY_BACKEND_ARGMAX_SCORES:-}" \
LLAMA_SPEC_VERIFY_BULK_SAMPLED_IDS="${LLAMA_SPEC_VERIFY_BULK_SAMPLED_IDS:-1}" \
LLAMA_SPEC_VERIFY_TOP2_PROFILE="${LLAMA_SPEC_VERIFY_TOP2_PROFILE:-}" \
LLAMA_SPEC_VERIFY_ACCEPT_PREFIX_PARITY="${LLAMA_SPEC_VERIFY_ACCEPT_PREFIX_PARITY:-}" \
LLAMA_SPEC_VERIFY_ACCEPT_PREFIX_ARGMAX="${LLAMA_SPEC_VERIFY_ACCEPT_PREFIX_ARGMAX:-}" \
LLAMA_MTP_DEFER_TARGET_H_NEXTN="${LLAMA_MTP_DEFER_TARGET_H_NEXTN:-1}" \
LLAMA_MTP_DRAFT_FAST_ARGMAX="${LLAMA_MTP_DRAFT_FAST_ARGMAX:-1}" \
LLAMA_MTP_DRAFT_DIRECT_ARGMAX_IDS="${LLAMA_MTP_DRAFT_DIRECT_ARGMAX_IDS:-1}" \
LLAMA_MTP_DRAFT_DIRECT_ARGMAX_UNROLL="${LLAMA_MTP_DRAFT_DIRECT_ARGMAX_UNROLL:-7}" \
LLAMA_GEMMA4_MTP_QONLY_ATTN_INPUTS="${LLAMA_GEMMA4_MTP_QONLY_ATTN_INPUTS:-1}" \
LLAMA_GEMMA4_MTP_FUSED_OUTPUT_ARGMAX="${LLAMA_GEMMA4_MTP_FUSED_OUTPUT_ARGMAX:-1}" \
LLAMA_GEMMA4_MOE_SELECTED_SOFTMAX="${LLAMA_GEMMA4_MOE_SELECTED_SOFTMAX:-1}" \
LLAMA_GEMMA4_MOE_SELECTED_SOFTMAX_FUSED="${LLAMA_GEMMA4_MOE_SELECTED_SOFTMAX_FUSED:-1}" \
LLAMA_GEMMA4_MOE_WEIGHTED_SUM="${LLAMA_GEMMA4_MOE_WEIGHTED_SUM:-1}" \
LLAMA_GEMMA4_MOE_REUSE_ATTN_RMS="${LLAMA_GEMMA4_MOE_REUSE_ATTN_RMS:-1}" \
LLAMA_GEMMA4_MOE_FUSED_DOWN_WEIGHTED_SUM_REORDER_VDR2="${LLAMA_GEMMA4_MOE_FUSED_DOWN_WEIGHTED_SUM_REORDER_VDR2:-1}" \
LLAMA_GEMMA4_FUSED_FINAL_POST_NORM_RESIDUAL="${LLAMA_GEMMA4_FUSED_FINAL_POST_NORM_RESIDUAL:-1}" \
LLAMA_GEMMA4_FUSED_ATTN_POST_NORM_RESIDUAL="${LLAMA_GEMMA4_FUSED_ATTN_POST_NORM_RESIDUAL:-}" \
LLAMA_GEMMA4_FUSED_PER_LAYER_POST_NORM_RESIDUAL="${LLAMA_GEMMA4_FUSED_PER_LAYER_POST_NORM_RESIDUAL:-}" \
LLAMA_SYCL_MUL_MAT_ID_ROUTE_CACHE="${LLAMA_SYCL_MUL_MAT_ID_ROUTE_CACHE:-1}" \
LLAMA_SYCL_F16_P021_SMALL_NCOLS="${LLAMA_SYCL_F16_P021_SMALL_NCOLS:-1}" \
GPU_INDEX="$GPU_INDEX" PORT="$PORT" \
CTX_SIZE="${CTX_SIZE:-8192}" BATCH_SIZE="${BATCH_SIZE:-1024}" UBATCH_SIZE="${UBATCH_SIZE:-1024}" THREADS="${THREADS:-8}" POLL="${POLL:-100}" \
CACHE_TYPE_K="${CACHE_TYPE_K:-f16}" CACHE_TYPE_V="${CACHE_TYPE_V:-f16}" FLASH_ATTN="${FLASH_ATTN:-off}" REASONING="${REASONING:-off}" \
CANARY_REPEATS="${CANARY_REPEATS:-128}" MAX_TOKENS="${MAX_TOKENS:-512}" \
REALISTIC_GATE="${REALISTIC_GATE:-1}" REALISTIC_METRIC_TOKENS="${REALISTIC_METRIC_TOKENS:-100}" \
EXTRA_LLAMA_ARGS="${EXTRA_LLAMA_ARGS:---parallel 1 --cache-ram 0 --spec-type draft-mtp --spec-draft-model $MTP_DRAFT_MODEL --spec-draft-n-max 3 --spec-draft-device SYCL0 --spec-draft-ngl all --spec-draft-type-k f16 --spec-draft-type-v f16 --spec-draft-n-min 2 --spec-draft-p-min 0.0475 --no-spec-draft-backend-sampling --spec-draft-threads 32 --spec-draft-threads-batch 32 --ctx-checkpoints 0}" \
LABEL="$LABEL" \
scripts/run-gemma4-26b-first-baseline.sh
