#!/usr/bin/env bash
set -euo pipefail

GPU_INDEX="${GPU_INDEX:-0}"
PORT="${PORT:-18260}"
HOST="${HOST:-127.0.0.1}"
MODEL="${MODEL:-/mnt/fast-ai/llm-models/gemma4-26b-a4b-it-q8-gguf/gemma-4-26B-A4B-it-UD-Q8_K_XL.gguf}"
LLAMA_SERVER="${LLAMA_SERVER:-/home/steve/src/llama.cpp-gemma-record-stack/build-sycl-b70-aot-bmg-g31/bin/llama-server}"
MODEL_ALIAS="${MODEL_ALIAS:-gemma4-26b-a4b-q8}"
CTX_SIZE="${CTX_SIZE:-8192}"
BATCH_SIZE="${BATCH_SIZE:-512}"
UBATCH_SIZE="${UBATCH_SIZE:-64}"
N_GPU_LAYERS="${N_GPU_LAYERS:-99}"
THREADS="${THREADS:-8}"
FLASH_ATTN="${FLASH_ATTN:-on}"
CACHE_TYPE_K="${CACHE_TYPE_K:-f16}"
CACHE_TYPE_V="${CACHE_TYPE_V:-f16}"
POLL="${POLL:-50}"
REASONING="${REASONING:-off}"
LLAMA_DEVICES="${LLAMA_DEVICES:-SYCL0}"
LLAMA_SPLIT_MODE="${LLAMA_SPLIT_MODE:-}"
LLAMA_TENSOR_SPLIT="${LLAMA_TENSOR_SPLIT:-}"
LLAMA_MAIN_GPU="${LLAMA_MAIN_GPU:-}"
EXTRA_LLAMA_ARGS="${EXTRA_LLAMA_ARGS:-}"
OUT_DIR="${OUT_DIR:-/mnt/fast-ai/bench-results/gemma4-26b-a4b-q8/servers}"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
LOG="${LOG:-$OUT_DIR/replica-gpu${GPU_INDEX}-port${PORT}-$STAMP.log}"

if [[ -f /opt/intel/oneapi/setvars.sh ]]; then
  # shellcheck disable=SC1091
  set +u
  source /opt/intel/oneapi/setvars.sh --force >/dev/null
  set -u
fi

export ONEAPI_DEVICE_SELECTOR="${ONEAPI_DEVICE_SELECTOR:-level_zero:$GPU_INDEX}"
export ZES_ENABLE_SYSMAN="${ZES_ENABLE_SYSMAN:-1}"
export UR_L0_ENABLE_RELAXED_ALLOCATION_LIMITS="${UR_L0_ENABLE_RELAXED_ALLOCATION_LIMITS:-1}"
export GGML_SYCL_DISABLE_OPT="${GGML_SYCL_DISABLE_OPT:-1}"

extra_args=()
if [[ -n "$EXTRA_LLAMA_ARGS" ]]; then
  read -r -a extra_args <<< "$EXTRA_LLAMA_ARGS"
fi
device_args=("-dev" "$LLAMA_DEVICES")
if [[ -n "$LLAMA_SPLIT_MODE" ]]; then
  device_args+=("-sm" "$LLAMA_SPLIT_MODE")
fi
if [[ -n "$LLAMA_TENSOR_SPLIT" ]]; then
  device_args+=("-ts" "$LLAMA_TENSOR_SPLIT")
fi
if [[ -n "$LLAMA_MAIN_GPU" ]]; then
  device_args+=("-mg" "$LLAMA_MAIN_GPU")
fi

mkdir -p "$OUT_DIR"

{
  echo "date_utc=$STAMP"
  echo "gpu_index=$GPU_INDEX"
  echo "host=$HOST"
  echo "port=$PORT"
  echo "model=$MODEL"
  echo "model_alias=$MODEL_ALIAS"
  echo "llama_server=$LLAMA_SERVER"
  echo "llama_cpp_commit=$(git -C "$(dirname "$LLAMA_SERVER")/../.." rev-parse --short HEAD 2>/dev/null || echo unknown)"
  echo "ctx_size=$CTX_SIZE"
  echo "batch_size=$BATCH_SIZE"
  echo "ubatch_size=$UBATCH_SIZE"
  echo "n_gpu_layers=$N_GPU_LAYERS"
  echo "threads=$THREADS"
  echo "flash_attn=$FLASH_ATTN"
  echo "cache_type_k=$CACHE_TYPE_K"
  echo "cache_type_v=$CACHE_TYPE_V"
  echo "poll=$POLL"
  echo "reasoning=$REASONING"
  echo "llama_devices=$LLAMA_DEVICES"
  echo "llama_split_mode=${LLAMA_SPLIT_MODE:-<unset>}"
  echo "llama_tensor_split=${LLAMA_TENSOR_SPLIT:-<unset>}"
  echo "llama_main_gpu=${LLAMA_MAIN_GPU:-<unset>}"
  echo "extra_llama_args=$EXTRA_LLAMA_ARGS"
  echo "LLAMA_MTP_DRAFT_TOP_K=${LLAMA_MTP_DRAFT_TOP_K:-<unset>}"
  echo "LLAMA_MTP_DRAFT_LOGIT_GAP_MIN=${LLAMA_MTP_DRAFT_LOGIT_GAP_MIN:-<unset>}"
  echo "LLAMA_MTP_DRAFT_FAST_TOPK=${LLAMA_MTP_DRAFT_FAST_TOPK:-<unset>}"
  echo "LLAMA_MTP_DRAFT_FAST_ARGMAX=${LLAMA_MTP_DRAFT_FAST_ARGMAX:-<unset>}"
  echo "LLAMA_MTP_DRAFT_DIRECT_ARGMAX_IDS=${LLAMA_MTP_DRAFT_DIRECT_ARGMAX_IDS:-<unset>}"
  echo "LLAMA_MTP_DRAFT_DIRECT_ARGMAX_UNROLL=${LLAMA_MTP_DRAFT_DIRECT_ARGMAX_UNROLL:-<unset>}"
  echo "LLAMA_MTP_DRAFT_DEVICE_H_HANDOFF=${LLAMA_MTP_DRAFT_DEVICE_H_HANDOFF:-<unset>}"
  echo "LLAMA_MTP_DRAFT_BACKEND_ARGMAX=${LLAMA_MTP_DRAFT_BACKEND_ARGMAX:-<unset>}"
  echo "LLAMA_MTP_DRAFT_BACKEND_TOPK=${LLAMA_MTP_DRAFT_BACKEND_TOPK:-<unset>}"
  echo "LLAMA_MTP_DRAFT_PROFILE=${LLAMA_MTP_DRAFT_PROFILE:-<unset>}"
  echo "LLAMA_SERVER_SPEC_PROFILE=${LLAMA_SERVER_SPEC_PROFILE:-<unset>}"
  echo "LLAMA_MTP_DRAFT_TERMINAL_LOGITS_ONLY=${LLAMA_MTP_DRAFT_TERMINAL_LOGITS_ONLY:-<unset>}"
  echo "LLAMA_MTP_DEFER_TARGET_H_NEXTN=${LLAMA_MTP_DEFER_TARGET_H_NEXTN:-<unset>}"
  echo "LLAMA_GEMMA4_MTP_FUSED_OUTPUT_ARGMAX=${LLAMA_GEMMA4_MTP_FUSED_OUTPUT_ARGMAX:-<unset>}"
  echo "LLAMA_GEMMA4_MTP_QONLY_ATTN_INPUTS=${LLAMA_GEMMA4_MTP_QONLY_ATTN_INPUTS:-<unset>}"
  echo "LLAMA_GEMMA4_MTP_LAYER_TAPER_AFTER=${LLAMA_GEMMA4_MTP_LAYER_TAPER_AFTER:-<unset>}"
  echo "LLAMA_GEMMA4_MTP_LAYER_TAPER_LAYERS=${LLAMA_GEMMA4_MTP_LAYER_TAPER_LAYERS:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_SELECTED_SOFTMAX=${LLAMA_GEMMA4_MOE_SELECTED_SOFTMAX:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_TOP_K=${LLAMA_GEMMA4_MOE_TOP_K:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_SORTED_TOP_K=${LLAMA_GEMMA4_MOE_SORTED_TOP_K:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_WEIGHTED_SUM=${LLAMA_GEMMA4_MOE_WEIGHTED_SUM:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_FUSED_ROUTER_SELECTED_WEIGHTS=${LLAMA_GEMMA4_MOE_FUSED_ROUTER_SELECTED_WEIGHTS:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_WEIGHTED_SUM_2D=${LLAMA_GEMMA4_MOE_WEIGHTED_SUM_2D:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_WEIGHTED_SUM_SELECTED_SOFTMAX=${LLAMA_GEMMA4_MOE_WEIGHTED_SUM_SELECTED_SOFTMAX:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_SELECTED_SOFTMAX_WEIGHTED_SUM=${LLAMA_GEMMA4_MOE_SELECTED_SOFTMAX_WEIGHTED_SUM:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_SKIP_EARLY_WEIGHTS_EXPAND=${LLAMA_GEMMA4_MOE_SKIP_EARLY_WEIGHTS_EXPAND:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_FUSED_DOWN_WEIGHTED_SUM=${LLAMA_GEMMA4_MOE_FUSED_DOWN_WEIGHTED_SUM:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_FUSED_DOWN_WEIGHTED_SUM_PARALLEL_SLOTS=${LLAMA_GEMMA4_MOE_FUSED_DOWN_WEIGHTED_SUM_PARALLEL_SLOTS:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_FUSED_DOWN_WEIGHTED_SUM_DIRECT_F32_PARALLEL_SLOTS=${LLAMA_GEMMA4_MOE_FUSED_DOWN_WEIGHTED_SUM_DIRECT_F32_PARALLEL_SLOTS:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_FUSED_DOWN_WEIGHTED_SUM_MATMUL_EPILOGUE=${LLAMA_GEMMA4_MOE_FUSED_DOWN_WEIGHTED_SUM_MATMUL_EPILOGUE:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_FUSED_GEGLU_DOWN_WEIGHTED_SUM=${LLAMA_GEMMA4_MOE_FUSED_GEGLU_DOWN_WEIGHTED_SUM:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_GEGLU_DOWN_MATMUL_EPILOGUE=${LLAMA_GEMMA4_MOE_GEGLU_DOWN_MATMUL_EPILOGUE:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_GATEUP_GEGLU=${LLAMA_GEMMA4_MOE_GATEUP_GEGLU:-<unset>}"
  echo "LLAMA_GEMMA4_MOE_FUSED_DOWN_WEIGHTED_SUM_DEBUG=${LLAMA_GEMMA4_MOE_FUSED_DOWN_WEIGHTED_SUM_DEBUG:-<unset>}"
  echo "LLAMA_SYCL_MUL_MAT_ID_MULTI_TOKEN_FAST=${LLAMA_SYCL_MUL_MAT_ID_MULTI_TOKEN_FAST:-<unset>}"
  echo "LLAMA_SYCL_MUL_MAT_ID_MULTI_TOKEN_NO_REORDER=${LLAMA_SYCL_MUL_MAT_ID_MULTI_TOKEN_NO_REORDER:-<unset>}"
  echo "LLAMA_SYCL_MUL_MAT_ID_MULTI_TOKEN_GROUPED_Q8_0=${LLAMA_SYCL_MUL_MAT_ID_MULTI_TOKEN_GROUPED_Q8_0:-<unset>}"
  echo "LLAMA_SYCL_MUL_MAT_ID_MULTI_TOKEN_PER_SLOT_Q8_0=${LLAMA_SYCL_MUL_MAT_ID_MULTI_TOKEN_PER_SLOT_Q8_0:-<unset>}"
  echo "LLAMA_SYCL_MUL_MAT_ID_MULTI_TOKEN_FILTER=${LLAMA_SYCL_MUL_MAT_ID_MULTI_TOKEN_FILTER:-<unset>}"
  echo "LLAMA_SYCL_MUL_MAT_ID_MULTI_TOKEN_NAME_SUBSTR=${LLAMA_SYCL_MUL_MAT_ID_MULTI_TOKEN_NAME_SUBSTR:-<unset>}"
  echo "LLAMA_SYCL_MUL_MAT_ID_GATE_UP_FAST_SEED_ROUTE_CACHE=${LLAMA_SYCL_MUL_MAT_ID_GATE_UP_FAST_SEED_ROUTE_CACHE:-<unset>}"
  echo "LLAMA_SYCL_MUL_MAT_ID_GATE_UP_Q8_SINGLETON_DIRECT=${LLAMA_SYCL_MUL_MAT_ID_GATE_UP_Q8_SINGLETON_DIRECT:-<unset>}"
  echo "LLAMA_SYCL_MUL_MAT_ID_ROUTE_CACHE=${LLAMA_SYCL_MUL_MAT_ID_ROUTE_CACHE:-<unset>}"
  echo "LLAMA_SYCL_MUL_MAT_ID_ROUTE_CACHE_INPLACE=${LLAMA_SYCL_MUL_MAT_ID_ROUTE_CACHE_INPLACE:-<unset>}"
  echo "LLAMA_SYCL_MUL_MAT_ID_ROUTE_CACHE_DEVICE_MAP=${LLAMA_SYCL_MUL_MAT_ID_ROUTE_CACHE_DEVICE_MAP:-<unset>}"
  echo "LLAMA_SPEC_VERIFY_GREEDY_ARGMAX=${LLAMA_SPEC_VERIFY_GREEDY_ARGMAX:-<unset>}"
  echo "LLAMA_SPEC_VERIFY_BACKEND_ARGMAX_IDS=${LLAMA_SPEC_VERIFY_BACKEND_ARGMAX_IDS:-<unset>}"
  echo "LLAMA_SPEC_VERIFY_FUSED_OUTPUT_ARGMAX=${LLAMA_SPEC_VERIFY_FUSED_OUTPUT_ARGMAX:-<unset>}"
  echo "ONEAPI_DEVICE_SELECTOR=$ONEAPI_DEVICE_SELECTOR"
  echo "GGML_SYCL_DISABLE_OPT=$GGML_SYCL_DISABLE_OPT"
  echo "GGML_SYCL_ENABLE_VMM=${GGML_SYCL_ENABLE_VMM:-<unset>}"
  echo "GGML_SYCL_DISABLE_GRAPH=${GGML_SYCL_DISABLE_GRAPH:-<unset>}"
  echo "GGML_SYCL_DISABLE_DNN=${GGML_SYCL_DISABLE_DNN:-<unset>}"
  "$LLAMA_SERVER" --version 2>&1 || true
  sycl-ls 2>&1 || true
  echo "--- server ---"
} > "$LOG"

exec > >(tee -a "$LOG") 2>&1
exec "$LLAMA_SERVER" \
  -m "$MODEL" \
  --alias "$MODEL_ALIAS" \
  --host "$HOST" \
  --port "$PORT" \
  "${device_args[@]}" \
  -ngl "$N_GPU_LAYERS" \
  -c "$CTX_SIZE" \
  -b "$BATCH_SIZE" \
  -ub "$UBATCH_SIZE" \
  -t "$THREADS" \
  --poll "$POLL" \
  -ctk "$CACHE_TYPE_K" \
  -ctv "$CACHE_TYPE_V" \
  -fa "$FLASH_ATTN" \
  --reasoning "$REASONING" \
  "${extra_args[@]}" \
  --jinja
