#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export MODEL_SLOT_NAME="${MODEL_SLOT_NAME:-qwen36-local-quality}"
export MODEL_SLOT_TITLE="${MODEL_SLOT_TITLE:-Qwen3.6 local quality lane}"
export MODEL_SLOT_HF_ID="${MODEL_SLOT_HF_ID:-nameistoken/Qwen3.6-35B-A3B-Quark-W8A8-INT8}"
export MODEL_SLOT_MODALITIES="${MODEL_SLOT_MODALITIES:-text}"
export MODEL_SLOT_STATUS="${MODEL_SLOT_STATUS:-quality-lane}"

export FRONTDOOR_HOST="${FRONTDOOR_HOST:-127.0.0.1}"
export FRONTDOOR_PORT="${FRONTDOOR_PORT:-18082}"
export FRONTDOOR_BACKEND_URL="${FRONTDOOR_BACKEND_URL:-http://127.0.0.1:18080}"
export FRONTDOOR_MAX_ACTIVE_GENERATIONS="${FRONTDOOR_MAX_ACTIVE_GENERATIONS:-1}"
export FRONTDOOR_QUEUE_TIMEOUT_S="${FRONTDOOR_QUEUE_TIMEOUT_S:-60}"
export FRONTDOOR_BACKEND_TIMEOUT_S="${FRONTDOOR_BACKEND_TIMEOUT_S:-7200}"
export FRONTDOOR_DRAIN_TIMEOUT_S="${FRONTDOOR_DRAIN_TIMEOUT_S:-300}"
export FRONTDOOR_DEFAULT_MAX_OUTPUT_TOKENS="${FRONTDOOR_DEFAULT_MAX_OUTPUT_TOKENS:-2048}"
export FRONTDOOR_MAX_OUTPUT_TOKENS="${FRONTDOOR_MAX_OUTPUT_TOKENS:-4096}"
export FRONTDOOR_PAUSE_FILE="${FRONTDOOR_PAUSE_FILE:-/tmp/qwen36-local-quality-frontdoor.pause}"
export FRONTDOOR_CHAT_TEMPLATE_KWARGS_JSON="${FRONTDOOR_CHAT_TEMPLATE_KWARGS_JSON:-{\"enable_thinking\":false}}"
export FRONTDOOR_SERVED_MODEL_NAME="${FRONTDOOR_SERVED_MODEL_NAME:-qwen36-35b-a3b-fp8}"
export FRONTDOOR_REWRITE_REQUEST_MODEL="${FRONTDOOR_REWRITE_REQUEST_MODEL:-1}"
export FRONTDOOR_LOG_EVENTS="${FRONTDOOR_LOG_EVENTS:-0}"

exec "$repo_dir/scripts/openai-lan-frontdoor.py"
