#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export MODEL_SLOT_NAME="${MODEL_SLOT_NAME:-gemma4-26b-a4b-q8-quad}"
export MODEL_SLOT_TITLE="${MODEL_SLOT_TITLE:-Gemma 4 26B A4B Q8 quad replica}"
export MODEL_SLOT_HF_ID="${MODEL_SLOT_HF_ID:-unsloth/gemma-4-26B-A4B-it-GGUF}"
export MODEL_SLOT_MODALITIES="${MODEL_SLOT_MODALITIES:-text}"
export MODEL_SLOT_STATUS="${MODEL_SLOT_STATUS:-temporary-production}"
export FRONTDOOR_HOST="${FRONTDOOR_HOST:-0.0.0.0}"
export FRONTDOOR_PORT="${FRONTDOOR_PORT:-8000}"
export FRONTDOOR_BACKEND_URL="${FRONTDOOR_BACKEND_URL:-http://127.0.0.1:19350}"
export FRONTDOOR_BACKEND_URLS="${FRONTDOOR_BACKEND_URLS:-http://127.0.0.1:19350,http://127.0.0.1:19351,http://127.0.0.1:19352,http://127.0.0.1:19353}"
export FRONTDOOR_MAX_ACTIVE_GENERATIONS="${FRONTDOOR_MAX_ACTIVE_GENERATIONS:-8}"
export FRONTDOOR_BACKEND_CAPACITIES="${FRONTDOOR_BACKEND_CAPACITIES:-2,2,2,2}"
export FRONTDOOR_QUEUE_TIMEOUT_S="${FRONTDOOR_QUEUE_TIMEOUT_S:-3600}"
export FRONTDOOR_BACKEND_TIMEOUT_S="${FRONTDOOR_BACKEND_TIMEOUT_S:-7200}"
export FRONTDOOR_PAUSE_FILE="${FRONTDOOR_PAUSE_FILE:-/home/steve/llm-optimizations/.pause-gemma4-26b-quad}"
export FRONTDOOR_LOG_EVENTS="${FRONTDOOR_LOG_EVENTS:-1}"

exec "$repo_dir/scripts/openai-lan-frontdoor.py"
