"""Regression checks for staged evidence retention and future closeout hygiene."""
import importlib.util
import json
from pathlib import Path
import subprocess
import tempfile
import unittest

SPEC = importlib.util.spec_from_file_location("hygiene", Path(__file__).with_name("check-repository-hygiene.py"))
HYGIENE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(HYGIENE)


class RepositoryHygieneTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        self.git("init", "-q")
        self.git("config", "user.name", "Fixture")
        self.git("config", "user.email", "fixture@example.invalid")
        self.write("source.py", "print('retained source')\n")
        self.git("add", "source.py")
        self.git("commit", "-qm", "initial source")

    def git(self, *args):
        return subprocess.check_output(["git", "-C", str(self.root), *args])

    def write(self, path, text):
        target = self.root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)
        return target

    def check(self, base="HEAD", threshold=1024):
        return HYGIENE.check(self.root, base, threshold)

    def closeout(self, link="[source](../../source.py)"):
        return "# Finished mechanism test\n\n" + "\n\n".join(
            f"## {heading}\n\n{link if heading == 'Evidence and patches' else 'Measured observation or explicit limitation.'}"
            for heading in HYGIENE.SECTIONS) + "\n"

    def test_large_warnings_read_staged_bytes_not_unstaged_content(self):
        self.write("evidence.bin.txt", "x" * 2048)
        self.git("add", "evidence.bin.txt")
        self.write("evidence.bin.txt", "smaller uncommitted edit")
        report = self.check()
        self.assertEqual(report["large_artifacts"][0]["bytes"], 2048)
        self.assertFalse(report["errors"])
        self.git("commit", "-qm", "retain large evidence")
        self.assertFalse(self.check()["large_artifacts"])

    def test_changed_large_existing_blob_warns_again(self):
        self.write("source.py", "x" * 2048)
        self.git("add", "source.py")
        self.assertEqual(len(self.check()["large_artifacts"]), 1)

    def test_generated_caches_fail_even_when_force_added_or_old(self):
        self.write(".gitignore", "*.pyc\n")
        self.write("tools/__pycache__/source.pyc", "generated bytes")
        self.git("add", "-f", "tools/__pycache__/source.pyc")
        self.assertIn("generated cache", self.check()["errors"][0]["reason"])
        self.git("commit", "-qm", "historical bad cache")
        self.assertTrue(self.check()["errors"])

    def test_new_closeout_requires_substance_and_tracked_evidence(self):
        self.write("experiments/lane/closeout.md", "# Done\n\nLooks fast.\n")
        self.git("add", "experiments/lane/closeout.md")
        errors = self.check()["errors"]
        self.assertTrue(any("missing sections" in e["reason"] for e in errors))
        self.assertTrue(any("tracked repository evidence" in e["reason"] for e in errors))
        self.write("experiments/lane/closeout.md", self.closeout())
        self.git("add", "experiments/lane/closeout.md")
        report = self.check()
        self.assertFalse(report["errors"])
        self.assertEqual(report["closeouts_checked"][0]["evidence"], ["source.py"])

    def test_placeholders_external_and_untracked_links_do_not_pass(self):
        self.write("experiments/lane/untracked.json", "{}")
        for content in (self.closeout("[data](untracked.json)"),
                        self.closeout("[outside](https://example.invalid/result)"),
                        self.closeout().replace("Measured observation or explicit limitation.", "<fill in: result>", 1)):
            with self.subTest(content=content):
                self.write("experiments/lane/CLOSEOUT.md", content)
                self.git("add", "experiments/lane/CLOSEOUT.md")
                self.assertTrue(self.check()["errors"])

    def test_marker_checks_an_arbitrarily_named_new_note(self):
        self.write("experiments/lane/result.md", "<!-- campaign-closeout -->\n# Result\n")
        self.git("add", "experiments/lane/result.md")
        self.assertTrue(self.check()["errors"])

    def test_marker_checks_a_preexisting_note_when_campaign_closes(self):
        self.write("experiments/lane/plan.md", "# Open experiment\n")
        self.git("add", "experiments/lane/plan.md")
        self.git("commit", "-qm", "plan")
        self.write("experiments/lane/plan.md", "<!-- campaign-closeout -->\n# Done\n")
        self.git("add", "experiments/lane/plan.md")
        self.assertTrue(self.check()["errors"])

    def test_template_examples_in_code_are_not_a_completed_record(self):
        self.write("experiments/lane/closeout.md", "# Planned format\n```markdown\n" + self.closeout() + "````\n")
        self.git("add", "experiments/lane/closeout.md")
        errors = self.check()["errors"]
        self.assertTrue(any("missing sections" in e["reason"] for e in errors))
        self.assertTrue(any("tracked repository evidence" in e["reason"] for e in errors))

    def test_symlink_to_external_evidence_does_not_satisfy_closeout(self):
        (self.root / "external-result").symlink_to("/tmp/not-part-of-repo")
        self.git("add", "external-result")
        self.write("experiments/lane/closeout.md", self.closeout("[data](../../external-result)"))
        self.git("add", "experiments/lane/closeout.md")
        self.assertTrue(any("tracked repository evidence" in e["reason"] for e in self.check()["errors"]))

    def test_preserved_historical_closeout_can_move_without_reformatting(self):
        self.write("old-closeout.md", "# Original frozen note\n")
        self.git("add", "old-closeout.md")
        self.git("commit", "-qm", "old evidence")
        self.git("mv", "old-closeout.md", "new-closeout.md")
        self.assertFalse(self.check()["errors"])

    def test_closing_atx_hashes_do_not_hide_empty_sections(self):
        content = self.closeout()
        for heading in HYGIENE.SECTIONS:
            content = content.replace(f"## {heading}\n", f"## {heading} ##\n")
        self.write("experiments/lane/closeout.md", content)
        self.git("add", "experiments/lane/closeout.md")
        self.assertFalse(self.check()["errors"])
        self.write("experiments/lane/closeout.md", content.replace(
            "Measured observation or explicit limitation.", ""))
        self.git("add", "experiments/lane/closeout.md")
        errors = self.check()["errors"]
        self.assertEqual(5, sum("section needs content" in e["reason"] for e in errors))

    def test_new_copy_of_retained_old_note_is_not_a_historical_move(self):
        original = "# Ordinary historical note\n"
        self.write("old-note.md", original)
        self.git("add", "old-note.md")
        self.git("commit", "-qm", "ordinary note")
        self.write("experiments/lane/copy-closeout.md", original)
        self.git("add", "experiments/lane/copy-closeout.md")
        self.assertTrue(any("missing sections" in e["reason"] for e in self.check()["errors"]))
        # Removing the old path can exempt one move, not two new copies.
        self.git("rm", "old-note.md")
        self.write("experiments/lane/second-closeout.md", original)
        self.git("add", "experiments/lane/second-closeout.md")
        self.assertEqual(1, len(self.check()["closeouts_checked"]))
        self.assertTrue(self.check()["errors"])

    def test_reference_style_links_are_evidence_but_unused_definitions_are_not(self):
        for link in ("[source][artifact]", "[Artifact][]", "[ARTIFACT]"):
            with self.subTest(link=link):
                content = self.closeout(link) + '\n[artifact]: ../../source.py "Source"\n'
                self.write("experiments/lane/closeout.md", content)
                self.git("add", "experiments/lane/closeout.md")
                report = self.check()
                self.assertFalse(report["errors"])
                self.assertEqual(["source.py"], report["closeouts_checked"][0]["evidence"])
        content = self.closeout("No evidence linked.") + '\n[artifact]: ../../source.py\n'
        self.write("experiments/lane/closeout.md", content)
        self.git("add", "experiments/lane/closeout.md")
        self.assertTrue(any("tracked repository evidence" in e["reason"] for e in self.check()["errors"]))

    def test_removing_existing_marker_does_not_disable_closeout_validation(self):
        self.write("experiments/lane/result.md", "<!-- campaign-closeout -->\n" + self.closeout())
        self.git("add", "experiments/lane/result.md")
        self.git("commit", "-qm", "completed campaign")
        self.write("experiments/lane/result.md", self.closeout())
        self.git("add", "experiments/lane/result.md")
        self.assertEqual(1, len(self.check()["closeouts_checked"]))
        self.assertFalse(self.check()["errors"])
        self.write("experiments/lane/result.md", "# Result\nLooks fast.\n")
        self.git("add", "experiments/lane/result.md")
        errors = self.check()["errors"]
        self.assertTrue(any("missing sections" in e["reason"] for e in errors))
        self.assertTrue(any("tracked repository evidence" in e["reason"] for e in errors))

    def test_event_base_handles_first_push_and_rejects_injected_revision(self):
        event = self.write("event.json", json.dumps({"before": "0" * 40}))
        base = HYGIENE.base_for_event(self.root, event)
        self.assertEqual(self.check(base)["changed_files"], 1)
        event.write_text(json.dumps({"before": "--help"}))
        with self.assertRaises(ValueError):
            HYGIENE.base_for_event(self.root, event)
        sha = self.git("rev-parse", "HEAD").decode().strip()
        event.write_text(json.dumps({"pull_request": {"base": {"sha": sha}}}))
        self.assertEqual(HYGIENE.base_for_event(self.root, event), sha)


if __name__ == "__main__":
    unittest.main()
